app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

Route::get('/', array('as'=> 'front.home', 'uses' => 'FrontHomeController@index'));

Route::get('aboutUs', array('as'=> 'front.aboutUs', 'uses' => 'FrontHomeController@aboutUs'));
Route::get('contact', array('as'=> 'front.contact', 'uses' => 'FrontHomeController@contact'));
Route::post('contact/store', array('as'=> 'front.feedback.create', 'uses' => 'FrontHomeController@createFeedback'));
Route::get('video/{slug}', array('as'=> 'front.post.detail', 'uses' => 'FrontHomeController@postDetail'));
Route::get('popular', array('as'=> 'front.popular', 'uses' => 'FrontHomeController@popularPost'));
Route::get('category/{slug}', array('as'=> 'front.category', 'uses' => 'FrontHomeController@getCategoryPost'));
Route::get('tag/{slug}', array('as'=> 'front.tag', 'uses' => 'FrontHomeController@getTagPost'));
Route::get('search', array('as'=> 'front.search', 'uses' => 'FrontHomeController@getSearchPost'));
Route::get('dmca', array('as'=> 'front.dmca', 'uses' => 'FrontHomeController@DMCA'));

Route::get('admin/login', array('as'=> 'admin.login', 'uses' => 'Auth\AdminAuthController@login'));
Route::post('admin/login', array('as'=> 'admin.login.post', 'uses' => 'Auth\AdminAuthController@loginPost'));

Route::group(['prefix' => 'admin'], function () {
	Route::get('home', array('as'=> 'admin.home', 'uses' => 'HomeController@index'));
	Route::get('logout', array('as'=> 'admin.logout', 'uses' => 'Auth\AdminAuthController@logout'));

	Route::get('userUserRevoke/{id}', array('as'=> 'admin.users.revokeuser', 'uses' => 'UserController@revoke'));
	Route::post('userBan', array('as'=> 'admin.users.ban', 'uses' => 'UserController@ban'));

	Route::resource('users', 'UserController');
	Route::resource('admins', 'AdminsController');
	Route::resource('categories', 'CategiriesController');
	Route::resource('sub-categories', 'SubCategiriesController');
	Route::resource('posts', 'PostsController');
	Route::resource('domains', 'DomainsController');
	Route::resource('tags', 'TagsController');
	Route::resource('names', 'NameController');

	Route::post('managePostTags/store', array('as'=> 'admin.postTags.store', 'uses' => 'PostsController@postTagsStore'));
	Route::post('manageNamesMeta/store', array('as'=> 'admin.namesMeta.store', 'uses' => 'PostsController@postNamesMetaStore'));
	
	// SettingsController
	Route::get('settings', array('as'=> 'admin.settings', 'uses' => 'SettingsController@index'));
	Route::post('settingsUpdate', array('as'=> 'admin.settings.update', 'uses' => 'SettingsController@store'));
	
	// FeedbackController
	Route::get('feedback', array('as'=> 'admin.feedback', 'uses' => 'FeedbackController@index'));
});
Route::get('{nameslug}/{postslug}', array('as'=> 'front.name', 'uses' => 'FrontHomeController@getNamePost'));

Route::get('sitemap', function(){
	ini_set('memory_limit', '1024M');
	set_time_limit(0); //60 seconds = 1 minute

    // create new sitemap object
    $sitemap = App::make("sitemap");

    $sitemap->add(URL::to('/'), '2012-08-25T20:10:00+02:00', '1.0', 'daily');
    $sitemap->add(URL::to('/popular'), '2016-02-09T20:10:00+02:00', '1.0', 'daily');
    $sitemap->add(URL::to('/aboutUs'), '2016-02-09T20:10:00+02:00', '1.0', 'daily');
    $sitemap->add(URL::to('/contact'), '2016-02-09T20:10:00+02:00', '1.0', 'daily');

    $categorys = DB::table('sub_categories')->orderBy('created_at', 'desc')->get();

	// add every category to the sitemap
	foreach ($categorys as $category)
	{
	    $sitemap->add(URL::route('front.category',$category->slug), $category->updated_at, '1.0', 'daily');
	}

	$tags = DB::table('tags')->orderBy('created_at', 'desc')->get();

	// add every tag to the sitemap
	if(!empty($tags)){
		foreach ($tags as $tags)
		{
		    $sitemap->add(URL::route('front.tag',$tags->slug), $tags->updated_at, '1.0', 'daily');
		}
	}

	$posts = DB::table('posts')->orderBy('created_at', 'desc')->get();

    // add every post to the sitemap
    foreach ($posts as $post)
    {
     	$images = array();
         
        $images[] = array(
            'url' => URL::to('/')."/public/upload/posts/".$post->image,
            'title' => $post->title,
            'caption' => $post->title
        );
         
        $sitemap->add(URL::route('front.post.detail',$post->slug), $post->updated_at, '1.0', 'daily', $images);
    }

    return $sitemap->render('xml');
});

Route::get('sitemapname', function(){
	ini_set('memory_limit', '1024M');
	set_time_limit(0); //60 seconds = 1 minute

    // create new sitemap object
    $sitemap = App::make("sitemap");

    $names = DB::table('names')->get();
	$posts = DB::table('posts')->orderBy('created_at', 'desc')->get();

    // add every post to the sitemap
    foreach ($posts as $key=>$post)
    {
    	if(!empty($post->name_title) && !empty($post->name_keyword) && !empty($post->name_description)){
	        if(!empty($names)){
	        	$images = array();
	         
		        $images[] = array(
		            'url' => URL::to('/')."/public/upload/posts/".$post->image,
		            'title' => $post->title,
		            'caption' => $post->title
		        );

		        foreach ($names as $nkey => $nvalue) {
		        	$sitemap->add(URL::route('front.name',[$nvalue->slug,$post->slug]), $post->updated_at, '1.0', 'daily', $images);
		        }
	        }
    	}

    }

    return $sitemap->render('xml');
});

resources/views/adminTheme/alert.blade.php
@if ($errors->any())
<script type="text/javascript">
	toastr.error('Please check the form below for errors', 'Error Alert', {timeOut: 5000})
</script>
@endif

@if ($message = Session::get('success'))
<script type="text/javascript">
	toastr.success('<?php echo $message; ?>', 'Success Alert', {timeOut: 5000})
</script>
<?php Session::forget('success');?>
@endif

@if ($message = Session::get('error'))
<script type="text/javascript">
	toastr.error('<?php echo $message; ?>', 'Error Alert', {timeOut: 5000})
</script>
<?php Session::forget('error');?>
@endif

@if ($message = Session::get('warning'))
<script type="text/javascript">
	toastr.warning('<?php echo $message; ?>', 'Warning Alert', {timeOut: 5000})
</script>
<?php Session::forget('warning');?>
@endif

@if ($message = Session::get('info'))
<script type="text/javascript">
	toastr.info('<?php echo $message; ?>', 'Information Alert', {timeOut: 5000})
</script>
<?php Session::forget('info');?>
@endif

resources/views/adminTheme/default.blade.php
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>{{ $projectTitle }} | Dashboard</title>
        <meta content='width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no' name='viewport'>
        <meta name="description" content="Developed By M Abdur Rokib Promy">
        <meta name="keywords" content="Admin, Bootstrap 3, Template, Theme, Responsive">
        <link rel="stylesheet" type="text/css" href="{{ asset('/adminTheme/css/select2.min.css') }}">
        <link rel="stylesheet" type="text/css" href="{{ asset('/adminTheme/js/select2.min.js') }}">
        <!-- bootstrap 3.0.2 -->
        <link href="{{ asset('/public/adminTheme/css/bootstrap.min.css') }}" rel="stylesheet">
        <!-- font Awesome -->
        <link href="{{ asset('/public/adminTheme/css/font-awesome.min.css') }}" rel="stylesheet">
        <!-- Ionicons -->
        <link href="{{ asset('/public/adminTheme/css/ionicons.min.css') }}" rel="stylesheet">
        <!-- iCheck for checkboxes and radio inputs -->
        <link href="{{ asset('/public/adminTheme/css/iCheck/all.css') }}" rel="stylesheet">
        <link href="{{ asset('/public/adminTheme/css/datepicker/datepicker3.css') }}" rel="stylesheet">
        <link href="{{ asset('/public/adminTheme/css/custom.css') }}" rel="stylesheet">
        <!-- bootstrap wysihtml5 - text editor -->
        <link href='http://fonts.googleapis.com/css?family=Lato' rel='stylesheet' type='text/css'>
        <!-- Theme style -->
        <link href="{{ asset('/public/adminTheme/css/style.css') }}" rel="stylesheet">

        <!-- jQuery 2.0.2 -->
        <script src="{{ asset('/public/adminTheme/js/jquery.js') }}"></script>
        <script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
        <link href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css" rel="stylesheet">
        
        <style type="text/css">
            #process_img{
                opacity: 0.7;
                position: fixed;
                text-align: center;
                top: 0;
                width: 80%;
                z-index: 1001;
                display: none;
                background: white;
                height: 100%;
            }
            #process_img img{
                position: relative;
                top: 40%;
            }
        </style>

        <script type="text/javascript">
            var current_page_url = "<?php echo URL::current(); ?>";
            var current_page_fullurl = "<?php echo URL::full(); ?>";
        </script>

        @yield('style')
    </head>
    <body class="skin-black">
        <!-- header logo: style can be found in header.less -->
        @include('adminTheme.header')

        <div class="wrapper row-offcanvas row-offcanvas-left">
            @include('adminTheme.sidebar')
            <aside class="right-side">
                <section class="content">
                    @include('adminTheme.alert')
                    @yield('content')
                </section>
            </aside><!-- /.right-side -->
        </div><!-- ./wrapper -->

        <div id="process_img" style="display: none;">
            <img src="/public/adminTheme/img/loading.gif"/>
        </div>

        <!-- jQuery UI 1.10.3 -->
        <script src="{{ asset('/public/adminTheme/js/jquery-ui-1.10.3.min.js') }}"></script>
        <!-- Bootstrap -->
        <script src="{{ asset('/public/adminTheme/js/bootstrap.min.js') }}"></script>
        <script src="{{ asset('/public/adminTheme/js/bootbox.js') }}"></script>
        <script src="{{ asset('/public/adminTheme/js/plugins/datepicker/bootstrap-datepicker.js') }}"></script>
        <script src="{{ asset('/public/adminTheme/js/Director/app.js') }}"></script>
        <script src="{{ asset('/public/adminTheme/js/jquery.form.min.js') }}"></script>
        <!-- Director dashboard demo (This is only for demo purposes) -->
        <script src="{{ asset('/public/adminTheme/js/crud.js') }}"></script>
        <script src="{{ asset('/public/adminTheme/js/custom.js') }}"></script>
        @yield('script')

    </body>
</html>

resources/views/adminTheme/header.blade.php
<header class="header">
    <a href="{{ URL::route('admin.home') }}" class="logo">
    {{ $projectTitle }}
    </a>
    <!-- Header Navbar: style can be found in header.less -->
    <nav class="navbar navbar-static-top" role="navigation">
        <!-- Sidebar toggle button-->
        <a href="#" class="navbar-btn sidebar-toggle" data-toggle="offcanvas" role="button">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        </a>
        <div class="navbar-right">
            <ul class="nav navbar-nav">
                <!-- User Account: style can be found in dropdown.less -->
                <li class="dropdown user user-menu">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                    <i class="fa fa-user"></i>
                    <span>{{ auth()->guard('admin')->user()->fullname }}<i class="caret"></i></span>
                    </a>
                    <ul class="dropdown-menu dropdown-custom dropdown-menu-right">
                        <li class="divider"></li>
                        <li>
                            <a href="{{ route('admin.settings') }}">
                            <i class="fa fa-gear fa-fw pull-right"></i>
                            Settings
                            </a>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <a href="{{ URL::route('admin.login') }}"><i class="fa fa-ban fa-fw pull-right"></i> Logout</a>
                        </li>
                    </ul>
                </li>
            </ul>
        </div>
    </nav>
</header>

resources/views/adminTheme/login.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
<title>{{ $projectTitle }}</title>
<!-- Bootstrap Core CSS -->
<link href="{{ asset('/public/adminTheme/css/bootstrap.min.css') }}" rel="stylesheet">
<link href="{{ asset('/public/adminTheme/css/login.css') }}" rel="stylesheet">
</head>
<body>
    <div class="container">
        @yield('content')
    </div>
</body>

<!-- jQuery -->
<script src="{{ asset('/public/adminTheme/js/jquery.js') }}"></script>
<script src="{{ asset('/public/adminTheme/js/TweenLite.min.js') }}"></script>
<script src="{{ asset('/public/adminTheme/js/login.js') }}"></script>
</html>

resources/views/adminTheme/sidebar.blade.php
<!-- Left side column. contains the logo and sidebar -->
<aside class="left-side sidebar-offcanvas">
    <!-- sidebar: style can be found in sidebar.less -->
    <section class="sidebar">
        <!-- Sidebar user panel -->
        <div class="user-panel">
            <div class="pull-left image">
                <img src="/public/adminTheme/img/avatar5.png" class="img-circle" alt="User Image" />
            </div>
            <div class="pull-left info">
                <p>Hello, {{ auth()->guard('admin')->user()->fullname }}</p>
            </div>
        </div>
        <!-- sidebar menu: : style can be found in sidebar.less -->
        <?php 
            $currentPageURL = URL::current(); 
            $pageArray = explode('/', $currentPageURL);
            $pageActive = isset($pageArray[4]) ? $pageArray[4] : 'test';
        ?>
        <ul class="sidebar-menu">
            <li class="{{ $pageActive == 'home' ? 'active' : ''  }}">
                <a href="{{ URL::route('admin.home') }}">
                <i class="fa fa-dashboard"></i> <span>Dashboard</span>
                </a>
            </li>
        </ul>
        <!-- <ul class="sidebar-menu">
            <li class="{{ $pageActive == 'users' ? 'active' : ''  }}">
                <a href="{{ URL::route('admin.users.index') }}">
                <i class="fa fa-users"></i> <span>Users</span>
                </a>
            </li>
        </ul> -->
        <ul class="sidebar-menu">
            <li class="{{ $pageActive == 'admins' ? 'active' : ''  }}">
                <a href="{{ URL::route('admin.admins.index') }}">
                <i class="fa fa-user"></i> <span>Admins</span>
                </a>
            </li>
        </ul>
        <ul class="sidebar-menu">
            <li class="{{ $pageActive == 'categories' ? 'active' : ''  }}">
                <a href="{{ URL::route('admin.categories.index') }}">
                <i class="fa fa-sitemap"></i> <span>Categories</span>
                </a>
            </li>
        </ul>
        <ul class="sidebar-menu">
            <li class="{{ $pageActive == 'sub-categories' ? 'active' : ''  }}">
                <a href="{{ URL::route('admin.sub-categories.index') }}">
                <i class="fa fa-sitemap"></i> <span>Sub Categories</span>
                </a>
            </li>
        </ul>
        <ul class="sidebar-menu">
            <li class="{{ $pageActive == 'posts' ? 'active' : ''  }}">
                <a href="{{ URL::route('admin.posts.index') }}">
                <i class="fa fa-desktop"></i> <span>Posts</span>
                </a>
            </li>
        </ul>
        <ul class="sidebar-menu">
            <li class="{{ $pageActive == 'tags' ? 'active' : ''  }}">
                <a href="{{ URL::route('admin.tags.index') }}">
                <i class="fa fa-tags"></i> <span>Tags</span>
                </a>
            </li>
        </ul>
        <ul class="sidebar-menu">
            <li class="{{ $pageActive == 'names' ? 'active' : ''  }}">
                <a href="{{ URL::route('admin.names.index') }}">
                <i class="fa fa-tags"></i> <span>Names</span>
                </a>
            </li>
        </ul>
        <ul class="sidebar-menu">
            <li class="{{ $pageActive == 'domains' ? 'active' : ''  }}">
                <a href="{{ URL::route('admin.domains.index') }}">
                <i class="fa fa-star"></i> <span>Domains</span>
                </a>
            </li>
        </ul>
        <ul class="sidebar-menu">
            <li class="{{ $pageActive == 'feedback' ? 'active' : ''  }}">
                <a href="{{ URL::route('admin.feedback') }}">
                <i class="fa fa-fw fa-comment"></i> <span>Feedback</span>
                </a>
            </li>
        </ul>
    </section>
    <!-- /.sidebar -->
</aside>